// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBGbVao2fqPAMpfUiY03sPqgE-0zEwX4',
    appId: '1:397693381447:web:f1b42a2e92d9907b32fa62',
    messagingSenderId: '397693381447',
    projectId: 'tata-47a2e',
    authDomain: 'tata-47a2e.firebaseapp.com',
    storageBucket: 'tata-47a2e.firebasestorage.app',
    measurementId: 'G-H8SKYG0TXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm2d79qNPp90dkpk0kqoLZR5_6pE9Slgc',
    appId: '1:397693381447:android:335122238948e76032fa62',
    messagingSenderId: '397693381447',
    projectId: 'tata-47a2e',
    storageBucket: 'tata-47a2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEGf0ffsMuRg1W2_Dky0tsB1TjXA1-s38',
    appId: '1:397693381447:ios:7817e882147f94b832fa62',
    messagingSenderId: '397693381447',
    projectId: 'tata-47a2e',
    storageBucket: 'tata-47a2e.firebasestorage.app',
    iosBundleId: 'com.tata',
  );
}
