// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfY4bWIiUV5QMarecfagq325RuBy1ySjU',
    appId: '1:583073638100:web:2adf44b7dadea5c8603d41',
    messagingSenderId: '583073638100',
    projectId: 'tata-5e72c',
    authDomain: 'tata-5e72c.firebaseapp.com',
    storageBucket: 'tata-5e72c.appspot.com',
    measurementId: 'G-SPFC0ZMLBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_am4hiAq6IV1vq2xzP1iK0Xp4rzqmWw',
    appId: '1:583073638100:android:ad750b2c7fc65ac8603d41',
    messagingSenderId: '583073638100',
    projectId: 'tata-5e72c',
    storageBucket: 'tata-5e72c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGMsIGXUxvs8tWA7cGjWDcfFzxRBo51bc',
    appId: '1:583073638100:ios:57d718e1eb727052603d41',
    messagingSenderId: '583073638100',
    projectId: 'tata-5e72c',
    storageBucket: 'tata-5e72c.appspot.com',
    iosBundleId: 'com.example.tata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGMsIGXUxvs8tWA7cGjWDcfFzxRBo51bc',
    appId: '1:583073638100:ios:57d718e1eb727052603d41',
    messagingSenderId: '583073638100',
    projectId: 'tata-5e72c',
    storageBucket: 'tata-5e72c.appspot.com',
    iosBundleId: 'com.example.tata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfY4bWIiUV5QMarecfagq325RuBy1ySjU',
    appId: '1:583073638100:web:dbfd1434cf38b9e1603d41',
    messagingSenderId: '583073638100',
    projectId: 'tata-5e72c',
    authDomain: 'tata-5e72c.firebaseapp.com',
    storageBucket: 'tata-5e72c.appspot.com',
    measurementId: 'G-QPNTW1LE42',
  );

}